/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppBackupRouteImport } from './routes/app.backup'
import { Route as AppCounterSaleRouteImport } from './routes/app.counter-sale'
import { Route as AppFormulaRouteImport } from './routes/app.formula'
import { Route as AppIssueVoucherRouteImport } from './routes/app.issue-voucher'
import { Route as AppItemsRouteImport } from './routes/app.items'
import { Route as AppProductionRouteImport } from './routes/app.production'
import { Route as AppPurchaseRouteImport } from './routes/app.purchase'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReturnsRouteImport } from './routes/app.returns'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppSetupRouteImport } from './routes/app.setup'
import { Route as AppStockRouteImport } from './routes/app.stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppCounterSaleRoute = AppCounterSaleRouteImport.update({
  id: '/counter-sale',
  path: '/counter-sale',
  getParentRoute: () => AppRoute,
} as any)
const AppFormulaRoute = AppFormulaRouteImport.update({
  id: '/formula',
  path: '/formula',
  getParentRoute: () => AppRoute,
} as any)
const AppIssueVoucherRoute = AppIssueVoucherRouteImport.update({
  id: '/issue-voucher',
  path: '/issue-voucher',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRoute = AppPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/accounts': typeof AppAccountsRoute
  '/app/backup': typeof AppBackupRoute
  '/app/counter-sale': typeof AppCounterSaleRoute
  '/app/formula': typeof AppFormulaRoute
  '/app/issue-voucher': typeof AppIssueVoucherRoute
  '/app/items': typeof AppItemsRoute
  '/app/production': typeof AppProductionRoute
  '/app/purchase': typeof AppPurchaseRoute
  '/app/reports': typeof AppReportsRoute
  '/app/returns': typeof AppReturnsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/setup': typeof AppSetupRoute
  '/app/stock': typeof AppStockRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/backup': typeof AppBackupRoute
  '/app/counter-sale': typeof AppCounterSaleRoute
  '/app/formula': typeof AppFormulaRoute
  '/app/issue-voucher': typeof AppIssueVoucherRoute
  '/app/items': typeof AppItemsRoute
  '/app/production': typeof AppProductionRoute
  '/app/purchase': typeof AppPurchaseRoute
  '/app/reports': typeof AppReportsRoute
  '/app/returns': typeof AppReturnsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/setup': typeof AppSetupRoute
  '/app/stock': typeof AppStockRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/accounts': typeof AppAccountsRoute
  '/app/backup': typeof AppBackupRoute
  '/app/counter-sale': typeof AppCounterSaleRoute
  '/app/formula': typeof AppFormulaRoute
  '/app/issue-voucher': typeof AppIssueVoucherRoute
  '/app/items': typeof AppItemsRoute
  '/app/production': typeof AppProductionRoute
  '/app/purchase': typeof AppPurchaseRoute
  '/app/reports': typeof AppReportsRoute
  '/app/returns': typeof AppReturnsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/setup': typeof AppSetupRoute
  '/app/stock': typeof AppStockRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/accounts'
    | '/app/backup'
    | '/app/counter-sale'
    | '/app/formula'
    | '/app/issue-voucher'
    | '/app/items'
    | '/app/production'
    | '/app/purchase'
    | '/app/reports'
    | '/app/returns'
    | '/app/sales'
    | '/app/setup'
    | '/app/stock'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/accounts'
    | '/app/backup'
    | '/app/counter-sale'
    | '/app/formula'
    | '/app/issue-voucher'
    | '/app/items'
    | '/app/production'
    | '/app/purchase'
    | '/app/reports'
    | '/app/returns'
    | '/app/sales'
    | '/app/setup'
    | '/app/stock'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/accounts'
    | '/app/backup'
    | '/app/counter-sale'
    | '/app/formula'
    | '/app/issue-voucher'
    | '/app/items'
    | '/app/production'
    | '/app/purchase'
    | '/app/reports'
    | '/app/returns'
    | '/app/sales'
    | '/app/setup'
    | '/app/stock'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/backup': {
      id: '/app/backup'
      path: '/backup'
      fullPath: '/app/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/counter-sale': {
      id: '/app/counter-sale'
      path: '/counter-sale'
      fullPath: '/app/counter-sale'
      preLoaderRoute: typeof AppCounterSaleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/formula': {
      id: '/app/formula'
      path: '/formula'
      fullPath: '/app/formula'
      preLoaderRoute: typeof AppFormulaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/issue-voucher': {
      id: '/app/issue-voucher'
      path: '/issue-voucher'
      fullPath: '/app/issue-voucher'
      preLoaderRoute: typeof AppIssueVoucherRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items': {
      id: '/app/items'
      path: '/items'
      fullPath: '/app/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/production': {
      id: '/app/production'
      path: '/production'
      fullPath: '/app/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase': {
      id: '/app/purchase'
      path: '/purchase'
      fullPath: '/app/purchase'
      preLoaderRoute: typeof AppPurchaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/returns': {
      id: '/app/returns'
      path: '/returns'
      fullPath: '/app/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBackupRoute: typeof AppBackupRoute
  AppCounterSaleRoute: typeof AppCounterSaleRoute
  AppFormulaRoute: typeof AppFormulaRoute
  AppIssueVoucherRoute: typeof AppIssueVoucherRoute
  AppItemsRoute: typeof AppItemsRoute
  AppProductionRoute: typeof AppProductionRoute
  AppPurchaseRoute: typeof AppPurchaseRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSetupRoute: typeof AppSetupRoute
  AppStockRoute: typeof AppStockRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBackupRoute: AppBackupRoute,
  AppCounterSaleRoute: AppCounterSaleRoute,
  AppFormulaRoute: AppFormulaRoute,
  AppIssueVoucherRoute: AppIssueVoucherRoute,
  AppItemsRoute: AppItemsRoute,
  AppProductionRoute: AppProductionRoute,
  AppPurchaseRoute: AppPurchaseRoute,
  AppReportsRoute: AppReportsRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSetupRoute: AppSetupRoute,
  AppStockRoute: AppStockRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
